export const agencies = [
    {
        id: "digital-marketing-pro-agency",
        name: "Digital Marketing Pro Agency",
        tagline: "Full-Service Digital Marketing Solutions",
        description:
            "We are a full-service digital marketing agency specializing in SEO, PPC, and content marketing. With over a decade of experience, we've helped businesses across various industries achieve their online marketing goals.\n\nOur data-driven approach and creative strategies ensure maximum ROI for our clients. We stay ahead of the latest digital marketing trends and technologies to deliver exceptional results.",
        location: "New York, USA",
        additionalLocations: ["Los Angeles", "Chicago", "Miami"],
        founded: 2010,
        teamSize: "50-100",
        services: [
            "SEO",
            "Content Marketing",
            "PPC Advertising",
            "Social Media Marketing",
        ],
        industries: ["E-commerce", "SaaS", "Healthcare", "Real Estate"],
        clientSize: ["Small Business", "Mid-Market", "Enterprise"],
        budgetRange: ["$5,000 - $10,000", "$10,000 - $25,000", "$25,000+"],
        projectDuration: ["3-6 months", "6-12 months", "Ongoing"],
        geographicFocus: ["North America", "Europe"],
        languages: ["English", "Spanish"],
        startingPrice: "$5,000",
        googleReview: {
            rating: 4.8,
            count: 156,
        },
        expertise: {
            seo: [
                "Technical SEO",
                "Local SEO",
                "E-commerce SEO",
                "International SEO",
            ],
            marketing: [
                "Content Strategy",
                "Email Marketing",
                "Social Media Management",
            ],
            development: ["WordPress", "Shopify", "Custom CMS"],
        },
    },
    {
        id: "tech-innovators-agency",
        name: "Tech Innovators Agency",
        tagline: "Cutting-Edge Web Development Solutions",
        description:
            "We are a technology-first agency focused on creating innovative web and mobile solutions. Our team of expert developers and designers craft beautiful, scalable applications that drive business growth.\n\nWe specialize in modern frameworks and cloud technologies, ensuring our clients stay ahead in the digital landscape.",
        location: "San Francisco, USA",
        additionalLocations: ["Seattle", "Austin"],
        founded: 2015,
        teamSize: "20-50",
        services: [
            "Web Development",
            "Mobile App Development",
            "Cloud Solutions",
            "UI/UX Design",
        ],
        industries: ["Technology", "Startups", "FinTech", "EdTech"],
        clientSize: ["Startup", "Mid-Market", "Enterprise"],
        budgetRange: ["$25,000 - $50,000", "$50,000 - $100,000", "$100,000+"],
        projectDuration: ["3-6 months", "6-12 months"],
        geographicFocus: ["North America", "Asia Pacific"],
        languages: ["English", "Mandarin"],
        startingPrice: "$25,000",
        googleReview: {
            rating: 4.9,
            count: 89,
        },
        expertise: {
            seo: ["Technical SEO", "App Store Optimization"],
            marketing: ["Product Marketing", "Growth Marketing"],
            development: ["React", "Node.js", "React Native", "AWS", "Azure"],
        },
    },
    {
        id: "creative-minds-agency",
        name: "Creative Minds Agency",
        tagline: "Innovative Design & Branding Solutions",
        description:
            "We transform brands through strategic design thinking and creative excellence. Our passionate team creates memorable brand experiences that resonate with audiences worldwide.\n\nFrom logo design to complete brand identity systems, we help businesses stand out in today's competitive market.",
        location: "London, UK",
        additionalLocations: ["Manchester", "Edinburgh", "Paris"],
        founded: 2012,
        teamSize: "10-20",
        services: [
            "Brand Design",
            "UI/UX Design",
            "Motion Graphics",
            "Print Design",
        ],
        industries: [
            "Fashion",
            "Luxury",
            "Food & Beverage",
            "Arts & Entertainment",
        ],
        clientSize: ["Small Business", "Mid-Market"],
        budgetRange: ["$10,000 - $25,000", "$25,000 - $50,000"],
        projectDuration: ["1-3 months", "3-6 months"],
        geographicFocus: ["Europe", "Middle East"],
        languages: ["English", "French", "Arabic"],
        startingPrice: "$10,000",
        googleReview: {
            rating: 4.7,
            count: 73,
        },
        expertise: {
            seo: ["Local SEO", "Visual SEO"],
            marketing: [
                "Brand Strategy",
                "Social Media Marketing",
                "Influencer Marketing",
            ],
            development: ["WordPress", "Webflow", "Shopify"],
        },
    },
    {
        id: "asia-digital-solutions",
        name: "Asia Digital Solutions",
        tagline: "Complete Digital Marketing for Asian Markets",
        description:
            "Specializing in digital marketing solutions for Asian markets, we help businesses expand their presence across the fastest-growing digital economies.\n\nOur deep understanding of local markets and consumer behavior enables us to create highly effective marketing strategies.",
        location: "Singapore",
        additionalLocations: ["Hong Kong", "Tokyo", "Seoul"],
        founded: 2016,
        teamSize: "50-100",
        services: [
            "Digital Marketing",
            "Market Research",
            "Social Media Marketing",
            "E-commerce Solutions",
        ],
        industries: ["Retail", "E-commerce", "Technology", "Consumer Goods"],
        clientSize: ["Mid-Market", "Enterprise"],
        budgetRange: ["$10,000 - $25,000", "$25,000 - $50,000", "$50,000+"],
        projectDuration: ["3-6 months", "6-12 months", "Ongoing"],
        geographicFocus: ["Asia Pacific"],
        languages: ["English", "Mandarin", "Japanese", "Korean"],
        startingPrice: "$10,000",
        googleReview: {
            rating: 4.6,
            count: 128,
        },
        expertise: {
            seo: ["Technical SEO", "Local SEO", "E-commerce SEO"],
            marketing: [
                "WeChat Marketing",
                "Line Marketing",
                "KakaoTalk Marketing",
            ],
            development: [
                "WeChat Mini Programs",
                "Line Mini Apps",
                "Cross-Border E-commerce",
            ],
        },
    },
    {
        id: "latam-growth-partners",
        name: "LATAM Growth Partners",
        tagline: "Digital Growth Experts for Latin America",
        description:
            "We specialize in helping businesses grow their digital presence across Latin America. Our team combines local market expertise with global best practices.\n\nFrom market entry strategies to ongoing digital marketing campaigns, we help brands succeed in the Latin American digital landscape.",
        location: "São Paulo, Brazil",
        additionalLocations: ["Mexico City", "Buenos Aires", "Bogotá"],
        founded: 2018,
        teamSize: "20-50",
        services: [
            "Market Entry Strategy",
            "Digital Marketing",
            "Social Media Management",
            "Content Marketing",
        ],
        industries: [
            "Retail",
            "Education",
            "Financial Services",
            "Consumer Goods",
        ],
        clientSize: ["Mid-Market", "Enterprise"],
        budgetRange: ["$5,000 - $10,000", "$10,000 - $25,000"],
        projectDuration: ["3-6 months", "6-12 months", "Ongoing"],
        geographicFocus: ["Latin America"],
        languages: ["Spanish", "Portuguese", "English"],
        startingPrice: "$5,000",
        googleReview: {
            rating: 4.7,
            count: 92,
        },
        expertise: {
            seo: ["Local SEO", "International SEO", "E-commerce SEO"],
            marketing: [
                "Social Media Strategy",
                "Influencer Marketing",
                "Content Marketing",
            ],
            development: ["WordPress", "WooCommerce", "Custom Development"],
        },
    },
];
